//! Represenattion of lipa na mpesa online paymentrequest api
//! 
//! Lipa na M-Pesa Online Payment API is used to initiate a M-Pesa transaction on behalf of a customer using STK
//! Push. This is the same technique mySafaricom App uses whenever the app is used to make payments. 
//! 
//! test url: POST https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest

/// A struct holding request parameters for the lipa na mpesa online api
#[derive(Debug)]
pub struct LipaNaMpesaOnlinePaymentRequest {
    /// The organization shortcode used to receive the transaction
    BusinessShortCode: String,
    /// The password for encrypting the request. This is generated by base64 encoding BusinessShortcode , Passkey and Timestamp
    Password: String,
    /// The timestamp of the transaction in the format **yyyymmddhhiiss** .
    Timestamp: String,
    /// The transaction type to be used for this request. Only `CustomerPayBillOnline` is supported.
    TransactionType: String,
    /// The amount to be transacted.
    Amount: String,
    /// The MSISDN sending the funds.
    PartyA: String,
    /// The organization shortcode receiving the funds
    PartyB: String,
    /// The MSISDN sending the funds.
    PhoneNumber: String,
    /// The url to where responses from M-Pesa will be sent to.
    CallBackURL: String,
    /// Used with M-Pesa PayBills
    AccountReference: String,
    /// A description of the transaction
    TransactionDesc: String,
    
}

/// Represenattion ofresponses expected form a lipn ana mpesa online mpesa api call
#[derive(Debug)]
pub enum LipaNaMpesaOnlinePaymentResponse {
    /// Merchant Request ID
    MerchantRequestID,
    /// Check out Request ID
    CheckoutRequestID,
    /// Response Code
    ResponseCode,
    /// Result Desc
    ResultDesc,
    /// Response Description message
    ResponseDescription,
    /// Result Code
    ResultCode,
}