//!Representation of the B2B Api
//! 
//! This API enables Business to Business (B2B) transactions between a business and another business. Use of this API
//! requires a valid and verified B2B M-Pesa short code for the business initiating the transaction and the both
//! businesses involved in the transaction.
//! 
//! testing url: POST https://sandbox.safaricom.co.ke/mpesa/b2b/v1/paymentrequest

/// Struct holding B2B request parameters
#[derive(Debug)]
pub struct B2B {
    /// This is the credential/username used to authenticate the transaction request
    Initiator: String,
    /// Base64 encoded string of the Security Credential, which is encrypted using M-Pesa public key and validates the transaction on M-Pesa Core system.
    SecurityCredential: String,
    /// Unique command for each transaction type, possible values are: BusinessPayBill, MerchantToMerchantTransfer, MerchantTransferFromMerchantToWorking, MerchantServicesMMFAccountTransfer, AgencyFloatAdvance
    CommandID: String,
    /// The amount being transacted
    Amount: String,
    /// Organization’s short code initiating the transaction
    PartyA: String,
    /// Type of organization sending the transaction
    SenderIdentifier: String,
    /// Organization’s short code receiving the funds being transacted
    PartyB: String,
    /// Type of organization receiving the funds being transacted.
    RecieverIdentifierType: String,
    /// Comments that are sent along with the transaction
    Remarks: String,
    /// The path that stores information of time out transactions.it should be properly
    ///validated to make sure that it contains the port, URI and domain name or publicly
    ///available IP.
    QueueTimeOutURL: String,
    /// The path that receives results from M-Pesa it should be properly validated to make
    /// sure that it contains the port, URI and domain name or publicly available IP.
    ResultURL: String,
    /// Account Reference mandatory for “BusinessPaybill” CommandID
    AccountReference: String,
}

/// Representation of responses expected from a B2B api call
#[derive(Debug)]
pub enum B2BResponse {
    /// A unique numeric code generated by the M-Pesa system of the response to a request.
    ConversationID,
    /// A unique numeric code generated by the M-Pesa system of the request.
    OriginatorConversationID,
    /// A response message from the M-Pesa system accompanying the response to a request.
    ResponseDescription,

}