//!Respresenation of the C2B Api
//! 
//! This API enables Paybill and Buy Goods merchants to integrate to M-Pesa and receive real time payments notifications.
//! Several apis are encapsulated in this:
//! * **Register Url** - The C2B Register URL API registers the 3rd party’s confirmation and validation URLs to M-Pesa ; which then maps
//!                     these URLs to the 3rd party shortcode. Whenever M-Pesa receives a transaction on the shortcode, M-Pesa triggers
//!                     a validation request against the validation URL and the 3rd party system responds to M-Pesa with a validation
//!                     response (either a success or an error code). The response expected is the success code the 3rd party
//!                     M-Pesa completes or cancels the transaction depending on the validation response it receives from the 3rd party
//!                     system. A confirmation request of the transaction is then sent by M-Pesa through the confirmation URL back to
//!                     the 3rd party which then should respond with a success acknowledging the confirmation.
//!                     testing url: POST [https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl](#)
//!                    
//!  ****Note: The 3rd party resource URLs for both confirmation and validation must be HTTPS in production. Validation is an optional feature that needs to be activated on M-Pesa, the owner of the shortcode needs to make this request for activation.****
//! 
//! * **Simulate Transaction** - The simulates transaction initiates a simulated transaction from the customers end
//! 
//! testing url: POST [https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate](#) 


/// A struct holding RegisterUrl request parameters
#[derive(Debug)]
pub struct RegisterUrl {
    /// Validation URL for the client.
    ValidationURL: String,
    /// Confirmation URL for the client
    ConfirmationURL: String,
    /// Default response type for timeout.
    ResponseType: String,
    /// The short code of the organization.
    ShortCode: String,
}

/// Representation of responses expected from a register url api call
#[derive(Debug)]
pub enum RegisterUrlResponse {
    /// A unique numeric code generated by the M-Pesa system of the response to a request
    ConversationID,
    /// A unique numeric code generated by the M-Pesa system of the request
    OriginatorConversationID,
    /// A response message from the M-Pesa system accompanying the response to a request.
    ResponseDescription
}

/// A struct Simulate Transaction request parameters
#[derive(Debug)]
pub struct SimulateTransaction {
    /// Unique command for each transaction type
    CommandID: String,
    /// The amount been transacted.
    Amount: String,
    /// MSISDN (phone number) sending the transaction, start with country code without the plus(+) sign
    MSISDN: String,
    /// Bill Reference Number (Optional)
    BillRefNumber: String,
    /// 6 digit M-Pesa Till Number or PayBill Number
    ShortCode: String,
}

/// Represenattion of responses expected from a simulare traansaction api call
#[derive(Debug)]
pub enum SimulateTransactionResponse {
    /// A unique numeric code generated by the M-Pesa system of the response to a request
    ConversationID,
    /// A unique numeric code generated by the M-Pesa system of the request.
    OriginatorConversationID,
    /// A response message from the M-Pesa system accompanying the response to a request
    ResponseDescription,
}